version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - ecommercedb
      # - elasticsearch
      - redis
    ports:
      - '9000:9000'
      - '7001:7001'
    env_file:
      - path: ./docker/docker.env
        require: true
  # searchdb:
  #   image: elasticsearch:8.12.0
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  redis:
    image: redis:7.2.4
    expose:
      - 6379
  ecommercedb:
    image: postgres:16
    ports:
      - '5432:5432'
    restart: always
    environment:
      - POSTGRES_DB=groccia
      - POSTGRES_USER=groccia_app_admin
      - POSTGRES_PASSWORD=app_admin_password
    volumes:
      - ecommerce-data:/var/lib/postgresql/data
  cmsdb:
    image: postgres:16
    ports:
      - '5433:5432'
    restart: always
    environment:
      - POSTGRES_DB=storefront
      - POSTGRES_USER=storefront_cms
      - POSTGRES_PASSWORD=cms_admin_password
    volumes:
      - cms-data:/var/lib/postgresql/data
volumes:
  ecommerce-data:
  cms-data:
