version: '3.8'

services:
  medusa:
    build: .
    depends_on:
      - postgres
      - elasticsearch
      - redis
    ports:
      - '9000:9000'
    environment:
      - DATABASE_URL=postgres://grocia_app_admin:app_admin_password@postgres:5432/grociadb
      - NODE_ENV=development
      - JWT_SECRET=jkasjdk79898%&/!askns
      - COOKIE_SECRET=somethingjkasjdk79898%&/!askns
      - DATABASE_TYPE=postgres
      - REDIS_URL=redis://cache
    volumes:
      - medusa_data:/data
  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
  redis:
    image: redis:latest
    container_name: cache
    expose:
      - 6379
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=grociadb
      - POSTGRES_USER=grocia_app_admin
      - POSTGRES_PASSWORD=app_admin_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  medusa_data:
  postgres_data:
